apiVersion: v1
kind: Service
metadata:
  name: product-deployment
spec:
  selector:
    app: product-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer